package wrappersdk.inin.com.purecloudandroidswaggertest;

import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.util.Log;
import android.view.View;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Button;
import android.widget.EditText;

import com.google.gson.Gson;

import io.swagger.client.ApiClient;
import io.swagger.client.Configuration;
import io.swagger.client.api.UsersApi;
import io.swagger.client.model.UserMe;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

public class MainActivity extends AppCompatActivity {
    private String Tag = "testswaggergradle";
    private EditText responsetext;
    private Button btnCallApi;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        responsetext = (EditText)findViewById(R.id.responsetext);
        btnCallApi = (Button)findViewById(R.id.btnCallApi);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        FloatingActionButton fab = (FloatingActionButton) findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Snackbar.make(view, "Calling get users me api through gradle", Snackbar.LENGTH_LONG)
                        .setAction("Action", null).show();
            }
        });

        btnCallApi.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                ApiClient defaultClient = Configuration.getDefaultApiClient();
                defaultClient.setBasePath("https://api.inindca.com");//Replace with your base path default is "https://api.mypurecloud.com"
                defaultClient.setAccessToken("u8Jxb7j4JRooBIZZ0cqfd6KF7DRVqstsBnR2oqCaQj95E1PjgujIH0cfEhBXRfVGHXPhIGkfZZ4D5dk5w8COWg");

/*              Replace with your access token generated by refering this links
                https://developer.mypurecloud.com/api/rest/authorization/index.html
                https://developer.mypurecloud.com/api/rest/postman/
*/

                Call<UserMe> userMeCall = defaultClient.createService(UsersApi.class).getUsersMe(null);

                userMeCall.enqueue(new Callback<UserMe>() {
                    @Override
                    public void onResponse(Call<UserMe> call, Response<UserMe> response) {
                        if(response.isSuccessful())
                        {
                            Gson gson = new Gson();
                            String json = gson.toJson(response.body());
                            responsetext.setText(json);
                            Log.d(Tag, json);
                            Log.d(Tag,response.body().toString());
                            Log.d(Tag, response.raw().toString());
                            Log.d(Tag,response.toString());
                        }
                        else
                        {
                            Log.d(Tag,"Not Successful");
                            Log.d(Tag,response.raw().toString());
                            responsetext.setText(response.raw().toString());

                        }
                    }

                    @Override
                    public void onFailure(Call<UserMe> call, Throwable t) {
                        Log.d(Tag,"onFailure");
                        responsetext.setText("onFailure");
                    }
                });
            }
        });
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
}
